# Generated by Copilot
import logging
import pandas as pd
from rdkit import Chem

from navidiv.diversity.utils import (
    GetRingSystems,
)
from navidiv.scorer import BaseScore


class RingScorer(BaseScore):
    """Handles fragment scoring and analysis for molecular datasets."""

    def __init__(
        self,
        output_path: str | None = None,
    ) -> None:
        """Initialize FragmentScore.

        Args:
            min_count_fragments (int): Minimum count for fragments to be
                considered.
            output_path (str | None): Path to save output files.
        """
        super().__init__(output_path=output_path)
        self._csv_name = "ring"

    def get_count(self, smiles_list: list[str]) -> tuple[pd.DataFrame, None]:
        """Calculate the percentage of each fragment in the dataset.

        Args:
            smiles_list (list[str]): List of SMILES strings.

        Returns:
            tuple: DataFrame with fragment info, None (for compatibility)
        """
        func_groups = []

        for smi in smiles_list:
            if smi == "None":
                continue
            grps = GetRingSystems(smi)
            if grps is None:
                continue
            func_groups.extend(grps)

        fragments, over_represented_fragments = self._from_list_to_count_df(
            smiles_list,
            func_groups,
        )
        self._fragments_df = fragments
        return fragments, over_represented_fragments

    def _count_substructure_in_smiles(self, smiles_list, fragment):
        """Check if ngram is in smiles"""
        self._mol_smiles = [
            Chem.MolFromSmiles(smiles)
            for smiles in smiles_list
            if smiles != "None"
        ]

        return len(
            [
                mol
                for mol in self._mol_smiles
                if mol.HasSubstructMatch(Chem.MolFromSmarts(fragment))
            ]
        )


    def _comparison_function(
        self,
        smiles: str | None = None,
        fragment: str | None = None,
        mol: Chem.Mol | None = None,
    ) -> bool:
        """Check if the fragment is present in the SMILES string or molecule."""
        if smiles is None and mol is None:
            return False
        if smiles is not None:
            mol = Chem.MolFromSmiles(smiles)
        if fragment is None or mol is None:
            return False
        mol_fragment = Chem.MolFromSmiles(fragment)
        if mol_fragment is None:
            return False
        try:
            return mol.HasSubstructMatch(mol_fragment)
        except ValueError:
            logging.exception(
                "Error in substructure match for fragment: %s", fragment
            )
            return False

