# Generated by Copilot
import logging
import time  # Generated by Copilot
from collections import Counter

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from rdkit import Chem


class BaseScore:
    """Handles fragment scoring and analysis for molecular datasets."""

    def __init__(
        self,
        output_path: str | None = None,
    ) -> None:
        """Initialize the BaseScore class.

        Args:
            min_count_fragments (int): Minimum count of fragments to consider.
            output_path (str | None): Path to save output files.
        """
        self._output_path = output_path
        self.add_num_atoms = True
        self._csv_name = "fragments"
        self._fragments_df = None
        self.selected_fragments = None
        self._min_count_fragments = 3
        self.overrepresented_fragments_min_perc = 20
        self.overrepresented_fragments = None
        self.selection_criteria = {
            "Count_perc_per_molecule": 1,
            "Count_perc": 1,
            "diff_median_score": -5,
            "median_score_fragment": 0,
        }

    def update_selection_criteria(
        self,
        selection_criteria: dict[str, float],
    ) -> None:
        """Update the selection criteria for overrepresented fragments.

        Args:
            selection_criteria (dict[str, float]): Dictionary of selection
                criteria.

        Example:
            selection_criteria = {
                "Count_perc_per_molecule": 1,
                "Count_perc": 1,
                "diff_median_score": -5,
                "median_score_fragment": 0,
            }
            fragment_scorer.update_selection_criteria(selection_criteria)
        """
        self.selection_criteria = selection_criteria

    def get_count(self, smiles_list: list[str]) -> tuple[pd.DataFrame, None]:
        """Calculate the percentage of each fragment in the dataset.

        Args:
            smiles_list (list[str]): List of SMILES strings.

        Returns:
            tuple: DataFrame with fragment info, None (for compatibility)
        """
        raise NotImplementedError(
            "get_count method must be implemented in subclasses."
        )

    def _comparison_function(
        self,
        smiles: str | None = None,
        fragment: str | None = None,
        mol: Chem.Mol | None = None,
    ) -> bool:
        """Check if the fragment is present in the SMILES string or molecule."""
        raise NotImplementedError(
            "_comparison_function method must be implemented in subclasses."
        )

    def additional_metrics(self):
        """Calculate additional metrics for the fragments."""
        return {}

    def add_score_metrics(
        self,
        smiles_list: list[str],
        scores: list[float],
        additional_columns_df: {} = {},
    ) -> pd.DataFrame:
        """Add score metrics to the DataFrame.

        Args:
            smiles_list (list[str]): List of generated SMILES strings.
            scores (list[float]): List of scores for the generated SMILES.

        Returns:
            pd.DataFrame: DataFrame with score metrics.
        """

        def process_fragment(
            fragment: str, smiles: list[str], scores: list[float]
        ) -> list[float]:
            # frag_mol = Chem.MolFromSmarts(fragment)
            # if frag_mol is None:
            #    return [0.0] * 9
            mol_score = [
                (sm, score)
                for score, sm in zip(scores, smiles, strict=False)
                if sm != "None"  # and Chem.MolFromSmiles(sm) is not None
            ]
            scores_all = [score for _, score in mol_score]
            contains_fragment_dict = {}
            for smiles, score in mol_score:
                if smiles not in contains_fragment_dict:
                    contains_fragment_dict[smiles] = self._comparison_function(
                        smiles=smiles, fragment=fragment
                    )

            scores_containing_fragment = [
                score
                for smiles, score in mol_score
                if contains_fragment_dict[smiles]  # type: ignore
            ]
            scores_not_containing_fragment = [
                score
                for smiles, score in mol_score
                if not contains_fragment_dict[smiles]  # type: ignore
            ]
            molecules_countaining_fragment = [
                smiles
                for smiles, score in mol_score
                if contains_fragment_dict[smiles]
            ]  # type: ignore

            if len(scores_containing_fragment) == 0:
                return [0.0] * 10
            try:
                mean_score = np.mean(scores_all)
                std_score = np.std(scores_all)
                mean_score_fragment = np.mean(scores_containing_fragment)
                std_score_fragment = np.std(scores_containing_fragment)
                median_score = np.median(scores_all)
                median_score_fragment = np.median(scores_containing_fragment)
                mean_score_not_fragment = np.mean(
                    scores_not_containing_fragment
                )
                std_score_not_fragment = np.std(scores_not_containing_fragment)
                median_score_not_fragment = np.median(
                    scores_not_containing_fragment
                )
                smiles_countaining_fragment = molecules_countaining_fragment
            except (ValueError, TypeError):
                logging.exception(
                    "Error calculating score metrics for fragment: %s",
                    fragment,
                )
                return [0.0] * 10
            return [
                mean_score,
                std_score,
                mean_score_fragment,
                std_score_fragment,
                median_score,
                median_score_fragment,
                mean_score_not_fragment,
                std_score_not_fragment,
                median_score_not_fragment,
                smiles_countaining_fragment,
            ]

        self._fragments_df = self._fragments_df[
            self._fragments_df["Count"] > self._min_count_fragments
        ]
        if self._fragments_df.shape[0] == 0:
            logging.warning(
                "No fragments found with count greater than %d",
                self._min_count_fragments,
            )
            return self._fragments_df
        self._fragments_df[
            [
                "mean_score",
                "std_score",
                "mean_score_fragment",
                "std_score_fragment",
                "median_score",
                "median_score_fragment",
                "mean_score_not_fragment",
                "std_score_not_fragment",
                "median_score_not_fragment",
                "molecules_countaining_fragment",
            ]
        ] = self._fragments_df.apply(
            lambda row: pd.Series(
                process_fragment(
                    row["Substructure"],
                    smiles_list,
                    scores,
                )
            ),
            axis=1,
        )
        if self.add_num_atoms:
            num_atoms = []
            for substructure in self._fragments_df["Substructure"]:
                mol = Chem.MolFromSmarts(substructure)
                if mol is not None:
                    num_atoms.append(mol.GetNumAtoms())
                else:
                    num_atoms.append(0)
            self._fragments_df["num_atoms"] = num_atoms
        self._fragments_df["diff_median_score"] = (
            self._fragments_df["median_score_fragment"]
            - self._fragments_df["median_score_not_fragment"]
        )
        # if file exists, append to it
        for col, value in additional_columns_df.items():
            self._fragments_df[col] = value
        self._fragments_df.to_csv(
            f"{self._output_path}/{self._csv_name}_with_score.csv",
            index=False,
            mode="a",
            header=not pd.io.common.file_exists(
                f"{self._output_path}/{self._csv_name}_with_score.csv"
            ),
        )
        return self._fragments_df

    def plot_count_histogram(
        self,
        title: str = "Fragment Count Histogram",
        xlabel: str = "Fragment Count",
        ylabel: str = "Frequency",
        bins: int = 50,
    ) -> None:
        """Plot a histogram of fragment counts.

        Args:
            title (str): Title of the histogram.
            xlabel (str): Label for the x-axis.
            ylabel (str): Label for the y-axis.
            bins (int): Number of bins in the histogram.
        """
        if self._fragments_df is None:
            raise ValueError("Fragments DataFrame is not initialized.")
        fig, ax = plt.subplots()
        ax = self._fragments_df["Count"].plot.hist(
            bins=bins,
            alpha=0.7,
            color="blue",
            edgecolor="black",
            ax=ax,
        )
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        plt.savefig(f"{self._output_path}/{self._csv_name}_histogram.png")
        plt.close(fig)

    def select_overrepresented_fragments(self):
        """Select overrepresented fragments based on the defined criteria."""
        self.selected_fragments = self._fragments_df.copy()
        if self._fragments_df is None:
            raise ValueError("Fragments DataFrame is not initialized.")
        for col, value in self.selection_criteria.items():
            if col not in self.selected_fragments.columns:
                continue
            self.selected_fragments = self.selected_fragments[
                self.selected_fragments[col] > value
            ]
        self.selected_fragments.to_csv(
            f"{self._output_path}/{self._csv_name}_selected_fragments.csv",
            index=False,
            mode="a",
            header=not pd.io.common.file_exists(
                f"{self._output_path}/{self._csv_name}_selected_fragments.csv"
            ),
        )
        return self.selected_fragments

    def get_score(
        self,
        smiles_list: list[str],
        scores: list[float],
        additional_columns_df: {} = {},
    ) -> pd.DataFrame:
        """Get the score for the fragments.

        Args:
            smiles_list (list[str]): List of generated SMILES strings.
            scores (list[float]): List of scores for the generated SMILES.

        Returns:
            pd.DataFrame: DataFrame with score metrics.
        """
        start_time = time.time()
        self.get_count(smiles_list)
        time_to_get_count = time.time()
        print(
            f"time to get count: {time_to_get_count - start_time:.2f} seconds"
        )
        unique_fragments = self._fragments_df["Substructure"].to_list()
        self.add_score_metrics(smiles_list, scores, additional_columns_df)
        if self.total_number_of_fragments == 0:
            unicity_ratio = 0.0
        else:
            unicity_ratio = (
                len(unique_fragments) / self.total_number_of_fragments * 100
            )
        for col, value in additional_columns_df.items():
            self._fragments_df[col] = value
        # self.select_overrepresented_fragments()
        dict_results = {
            "Percentage of Unique Fragments": unicity_ratio,
            "Total Number of Fragments": self.total_number_of_fragments,
            "Number of Unique Fragments": len(unique_fragments),
            # "Selected Fragments": self.selected_fragments.shape[0],
            "Unique Fragments": unique_fragments,
        }
        dict_results = {**dict_results, **self.additional_metrics()}
        elapsed_time = time.time() - time_to_get_count
        print(f"time to get added score metrics {elapsed_time:.2f} seconds")

        return dict_results

    # Generated by Copilot

    def _from_list_to_count_df(
        self,
        smiles_list: list[str],
        substructure_list: list[str],
        total_number_of_ngrams: int | None = None,
    ) -> tuple[pd.DataFrame, None]:
        ngrams_counter = Counter(substructure_list)
        if total_number_of_ngrams is None:
            total_number_of_ngrams = len(substructure_list)
        self.total_number_of_fragments = total_number_of_ngrams
        ngrams_df = pd.DataFrame(
            {
                "Substructure": list(ngrams_counter.keys()),
                "Count": list(ngrams_counter.values()),
            }
        )
        ngrams_df["Count ratio"] = (
            ngrams_df["Count"] / total_number_of_ngrams
        ) * 100
        ngrams_df = ngrams_df.sort_values(by="Count ratio", ascending=False)
        ngrams_df = ngrams_df.reset_index(drop=True)
        ngrams_df["Molecules_with_Fragment"] = ngrams_df["Substructure"].apply(
            lambda x: self._count_substructure_in_smiles(smiles_list, x)
        )

        ngrams_df["Ratio_of Molecules_with_Fragment"] = (
            ngrams_df["Molecules_with_Fragment"] / len(smiles_list)
        ) * 100
        if self._output_path:
            try:
                ngrams_df.to_csv(
                    f"{self._output_path}/{self._csv_name}.csv",
                    index=False,
                )
            except OSError:
                logging.exception(
                    "Error saving fragments CSV for output_path: %s",
                    self._output_path,
                )
        self._fragments_df = ngrams_df
        return ngrams_df, None

    def _count_substructure_in_smiles(self, smiles, ngram):
        """Check if ngram is in smiles"""
        raise NotImplementedError(
            "_subs_in_smiles method must be implemented in subclasses."
        )
