import glob
import os
import subprocess
from pathlib import Path

import plotly.io as pio
import streamlit as st

from navidiv.app_utils.plot_generated_molecules import (
    plot_generated_molecules,
    plot_generated_molecules_from_file,
)
from navidiv.app_utils.plot_results import plot_results, plot_step_results
from navidiv.utils import get_smiles_column


def initialize_app():
    """Initialize the Streamlit app settings."""
    st.set_page_config(layout="wide", initial_sidebar_state="auto")
    pio.templates.default = "plotly"
    st.title("Analyse Generated Molecules")
    return True


# Generated by Copilot
def do_tsne(file_path):
    """Run t-SNE analysis on the provided CSV file.

    Args:
        file_path (str): Path to the CSV file containing molecular data.

    Returns:
        bool: True if t-SNE analysis was successful, False otherwise.
    """
    step_increment = st.sidebar.number_input(
        "step increment", min_value=1, max_value=100, value=10, step=1
    )
    if st.sidebar.button("Run t-SNE"):
        cmd = [
            "python3",
            "src/navidiv/get_tsne.py",
            "--df_path",
            file_path,
            "--step",
            str(step_increment),
        ]
        try:
            subprocess.run(cmd, check=True)
            st.success("t-SNE analysis complete.")
            st.session_state.file_path = file_path.replace(".csv", "_TSNE.csv")
            return True
        except Exception as e:
            st.error(f"Error running t-SNE: {e}")
    return False


def on_change_file_path():
    st.session_state.file_path = st.session_state.file_path_input


# Streamlit app
def main() -> None:
    """Main entry point for the Streamlit app.

    Handles UI and file selection.
    """
    initialised = initialize_app()

    if initialised:
        col1, col2, col3 = st.columns(3)
        with col1:
            # if st.button("Upload CSV file"):
            col_loading = st.columns(2)
            with col_loading[0]:
                val = st.text_input(
                    "Enter the path to your CSV file",
                    key="file_path_input",
                    on_change=on_change_file_path,
                )
            with col_loading[1]:
                if st.button("Load CSV file"):
                    if not val:
                        st.error("Please enter a valid file path.")
                    else:
                        st.session_state.file_path = val
                        st.success(
                            f"File loaded: {st.session_state.file_path}"
                        )
            if val:
                do_tsne(st.session_state.file_path)

                filtered_data = plot_generated_molecules_from_file(
                    st.session_state.file_path
                )
        with col2:
            if hasattr(st.session_state, "output_path"):
                if not os.path.exists(st.session_state.output_path):
                    os.makedirs(st.session_state.output_path)
                csv_files = [
                    Path(files).relative_to(st.session_state.output_path)
                    for files in glob.glob(
                        f"{st.session_state.output_path}/*/group*.csv"
                    )
                ]

                file_path_results = st.selectbox(
                    "Select a CSV file from folder", csv_files
                )
                if file_path_results:
                    plot_results(
                        f"{st.session_state.output_path}/{file_path_results}"
                    )
        if (
            hasattr(st.session_state, "list_of_molecules_containing_fragment")
            and st.session_state.list_of_molecules_containing_fragment
        ):
            with col1:
                st.write(
                    "#### Molecules containing fragment from previous step"
                )
                filtered_data["Molecules containing fragment"] = filtered_data[
                    get_smiles_column(filtered_data)
                ].apply(
                    lambda x: x
                    in st.session_state.list_of_molecules_containing_fragment
                )

                plot_generated_molecules(
                    filtered_data,
                    symbol_column="Molecules containing fragment",
                )
        with col3:
            if hasattr(st.session_state, "output_path"):
                if not os.path.exists(st.session_state.output_path):
                    os.makedirs(st.session_state.output_path)
                csv_files = [
                    Path(files).relative_to(st.session_state.output_path)
                    for files in glob.glob(
                        f"{st.session_state.output_path}/*/step_*.csv"
                    )
                ]

                file_path_results = st.selectbox(
                    "Select a CSV file from folder",
                    csv_files,
                    key="file_path_results",
                )
                if file_path_results:
                    plot_step_results(
                        f"{st.session_state.output_path}/{file_path_results}"
                    )


if __name__ == "__main__":
    main()
# Generated by Copilot
