
run_type = "transfer_learning"
device = "cuda:0"
tb_logdir = "/media/mohammed/Work/Navi_diversity/reinvent_runs/TL/output/tb_TL"

[parameters]

num_epochs = 50
save_every_n_epochs = 2
batch_size = 100
sample_batch_size = 2000

input_model_file = "/media/mohammed/Work/REINVENT4/priors/reinvent.prior"
output_model_file = "/media/mohammed/Work/Navi_diversity/reinvent_runs/TL/output/model/TL_reinvent.model"
smiles_file = "/media/mohammed/Work/Navi_diversity/reinvent_runs/TL/TL_train.csv"
validation_smiles_file = "/media/mohammed/Work/Navi_diversity/reinvent_runs/TL/TL_validation.csv"
standardize_smiles = false
randomize_smiles = true
randomize_all_smiles = false
internal_diversity = true
