#!/bin/bash

# Generated by Copilot

# Check if conda is available
if ! command -v conda &> /dev/null
then
    echo "conda could not be found. Please install Anaconda or Miniconda."
    exit 1
fi

ENV_NAME="OPTMOLGEN2"
export PYTHONPATH="${PYTHONPATH}:/media/mohammed/Work/SF_generative/script"
python_script_path="/media/mohammed/Work/Navi_diversity/src/navidiv/reinvent/"
config_path="/media/mohammed/Work/Navi_diversity/reinvent_runs/conf_folder"
config_name="test"

run_name=Full_Filters_long
wd="/media/mohammed/Work/Navi_diversity/reinvent_runs/runs/test/$run_name"
smart_list_path="$wd/full_smartlist.txt"
mkdir -p $wd

conda run -n $ENV_NAME python3 $python_script_path/run_reinvent_2.py --config-name $config_name --config-path $config_path  name=stage0 wd=$wd reinvent_common.max_steps=10000 