# Default configuration for REINVENT transfer learning

run_type = "transfer_learning"
device = "cuda:0"
tb_logdir = "reinvent_plugins/TL/tb_TL"

[parameters]
num_epochs = 50
save_every_n_epochs = 2
batch_size = 100
sample_batch_size = 2000

input_model_file = "reinvent_plugins/TL/model/stage1_checkpoint.model"
output_model_file = "reinvent_plugins/TL/model/TL_reinvent.model"
smiles_file = "reinvent_plugins/TL/TL_train.csv"
validation_smiles_file = "reinvent_plugins/TL/TL_validation.csv"
standardize_smiles = true
randomize_smiles = true
randomize_all_smiles = false
internal_diversity = true
