import time  # Generated by Copilot

import pandas as pd

from navidiv import (
    cluster_similarity_scorer,
)
from navidiv.utils import get_smiles_column


def test_cluster_scorer(df):
    """Test the cluster similarity scorer."""
    cluster_score = cluster_similarity_scorer.ClusterSimScorer(
        output_path="/media/mohammed/Work/Navi_diversity/examples/resultstest/",
        threshold=0.25,
    )
    start = time.time()  # Generated by Copilot
    scores_cluster = cluster_score.aggregate_df(df)
    cluster_score._fragments_df.to_csv(
        f"{cluster_score._output_path}/aggregate_fragments_with_score.csv",
        index=False,
    )  # Generated by Copilot
    end = time.time()  # Generated by Copilot
    print(
        f"ClusterSimilarityScorer.get_score time: {end - start:.3f} seconds"
    )  # Generated by Copilot
    print("Cluster scores")
    print("scores", scores_cluster)
    return scores_cluster


if __name__ == "__main__":
    csv_file = "/media/mohammed/Work/Navi_diversity/reinvent_runs/runs/test/test2/stage0/results/clusters/groupby_results_clusters.csv"
    df = pd.read_csv(csv_file).sample(frac=0.1).reset_index(drop=True)
    # df = df[df["step"] == 1000]
    print("columns", df.columns)
    smiles_col = get_smiles_column(df)
    df = df.dropna(subset=[smiles_col])

    test_cluster_scorer(df)

    print("done")
