  run_type: "staged_learning"
  smart_list_path: "None"
  prior_filename: "/media/mohammed/Work/Navi_diversity/reinvent_runs/SF_files/model/formed.prior"
  agent_filename: "/media/mohammed/Work/Navi_diversity/reinvent_runs/SF_files/model/formed.prior"
  avoid_filename: []
  max_steps: 1000
  batch_size: 128
  include_inception: true
  diversity_filter:
    div_type: "IdenticalMurckoScaffold" # choice between NoFilter ScaffoldOnly RSOnly AllFilters
    minscore: 0.1
    bucket_size: 100
  learning_strategy:
    type: "dap"
    sigma: 64
    lr: 0.0001
  include_rdkit_requirements: false
  include_scaffold_score: false
  include_molecular_weight: true
  include_SA_score: true
  ngram_filter:
    include: true
    ngram_size: 10
    min_count_ngram_ratio: 0.1
  fragment_filter: 
    include: true
    min_count_fragments: 10
    diff_median_score_limit: 0.1
    smart_list: ["[#6;R0]~[#6;R0]"]
  scaffold_filter: 
    include: true
    type: "csk_bm"
  dissimilarity_filter:
    include: true
    threshold: 0.2
    frag: ["CCCCCCCCCCCCCCC"]
  
  check_diversity: true # if false you can not use the fragment filter and the ngram filter
  check_diversity_every: 30